#!/usr/bin/env sh

gem install bundler --conservative
bundle check || bundle install
yarn
[ -r "config/database.yml" ] || cp config/database.yml.sample config/database.yml
bin/rails db:prepare
bin/rails log:clear tmp:clear
