name: 'CI'
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
      - name: Read node version
        id: read_node_version
        run: echo "version=$(cat .node-version)" >> $GITHUB_OUTPUT
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.read_node_version.outputs.version }}
      - name: Set up rails
        run: script/setup
      - name: Run RSpec
        run: bin/rspec
